### ISSUE TITLE
Install using Carthage

### ISSUE THREAD

**Issue by CraigSiemens** [pointfreeco/combine-schedulers#30]
Currently this can only be installed with SPM, it'd be nice if it could be installed with Carthage as well.

Would that be a PR you'd be willing to accept? I was thinking it could be done in a similar way to how swift-snapshot-testing does it (with xcodegen creating the project).

**Comment by stephencelis** [comment]
Hi @CraigSiemens, now that SPM has had built-in support in Xcode for a few years, we've decided to stop supporting Carthage and CocoaPods in our libraries. There's unfortunately a big maintenance cost in supporting these tools. We'll likely even eliminate existing support for them in projects like swift-snapshot-testing in the future.

While I understand that your project uses Carthage, can you use SPM for certain modules, like combine-schedulers, instead? If not, can you fork the project and set up Carthage from there?

**Comment by CraigSiemens** [comment]
Yeah that makes sense from a library maintenance perspective.

For us we'd like to keep using Carthage until SPM gets support for caching builds (it really speeds up out build time on CI) and more of our libraries support it. Forking is probably our best option at this point.

**Comment by stephencelis** [comment]
Thanks for understanding! Do `.xcframework`s help in any way? We haven't looked into it, but if this is a way of distributing builds via SPM that eliminates the issue, let us know if you'd like to help figure it out!

**Comment by CraigSiemens** [comment]
Distributing an XCFramework would still require the creation of an Xcode project to build it since SPM doesn't have a way to create any kind of framework from the package.

The solution I ended up going with was:
- Add this package and it's dependencies to our `Cartfile`.
- Run `carthage checkout`
- In the two packages run `swift package generate-xcodeproj`
- Run `carthage build`

This put an Xcode project in the location carthage was expecting. Then carthage could run `xcodebuild` with the project and set the correct build setting to produce a framework. It's a little wierd that we have to add the dependencies ourselves, but this was only a ~6 line change in our project so it was fairly simple.

---

I also came across https://github.com/unsignedapps/swift-create-xcframework which looks like it could build an xcframework from a package. It could be used if you want distribute a binary using carthage. It'd probably require some CI setup, but at least it avoids the duplication between the package and the xcodeproj.

**Comment by stephencelis** [comment]
> I also came across https://github.com/unsignedapps/swift-create-xcframework which looks like it could build an xcframework from a package. It could be used if you want distribute a binary using carthage. It'd probably require some CI setup, but at least it avoids the duplication between the package and the xcodeproj.

We're definitely down to add a GitHub workflow that builds an XCFramework this way for tagged releases. We already have one for generating documentation. If you have any luck, please do submit a PR!
