### ISSUE TITLE
Cannot archive build on Xcode 13 beta 3

### ISSUE THREAD

**Issue by d-date** [pointfreeco/combine-schedulers#31]
**Describe the bug**

When running archive build on Xcode 13 beta 3, the build fail since it depends on Combine.framework built by different compiler version.

> Failed to build module 'Combine'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.24.14 clang-1300.0.25.10)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.24.13 clang-1300.0.25.10)'). Please select a toolchain which matches the SDK.

**Screenshots**
<img width="864" alt="Screen Shot 2021-07-15 at 13 36 50" src="https://user-images.githubusercontent.com/20222809/125729582-34a9ce13-f47f-4850-9716-bf8f4bf6905f.png">

**Environment**
 - Xcode 13 beta 3
 - Swift 5.5

**Comment by stephencelis** [comment]
Hi @d-date! I'm able to successfully build a project that depends on CombineSchedulers in beta 3. The error message you posted makes it sound like you have a custom toolchain selected in Xcode. Can you check the "Xcode > Toolchains" menu and verify that "Xcode 13.0" is selected?

The only other thing I can think of is maybe you have some stale build products getting in the way. "Product > Clean Build Folder" could help, or you could try fully [deleting the Derived Data](https://programmingwithswift.com/delete-derived-data-xcode/) folder.

**Comment by d-date** [comment]
@stephencelis  
Did you succeed in the **Archive**, right?
 I'm able to build and run, but archive has failed.

As you say, I checked that Xcode 13 was selected as the toolchain. I also tried a clean build, but didn't change.

<img width="789" alt="Screen Shot 2021-07-15 at 22 56 49" src="https://user-images.githubusercontent.com/20222809/125800252-dffc0d9b-b167-4d67-a5d6-784d0a3ac404.png">

<img width="783" alt="Screen Shot 2021-07-15 at 23 01 03" src="https://user-images.githubusercontent.com/20222809/125800867-177991c7-1d98-46bd-8e14-7550fbabc4c7.png">

**Comment by kamcma** [comment]
I am also seeing this error. Although to start I am suspecting beta 3 or maybe something about my workspace configuration more than combine-schedulers per se.

I don't think I have any alternative toolchains installed. (The toolchain items don't even appear in the Xcode menu or Preferences > Components.) Deleted derived data. M1 Mac, if it matters.

**Comment by kamcma** [comment]
Seems to be the same issue:

https://developer.apple.com/forums/thread/682285?answerId=682006022#682006022

**Comment by mbrandonw** [comment]
😢 oof, good to know. 

I'm going to covert this to a discussion since it's not really a CombineSchedulers issue and so that we can continue sharing information about it.
