### ISSUE TITLE
EXC_BAD_ACCESS crash with iOS 15.2

### ISSUE THREAD

**Issue by FlyDaddyDev** [pointfreeco/combine-schedulers#49]
**Describe the bug**
When adding a type erased dispatch queue to my composable architecture environment, I found a run time error that occurs when the queue is erased to AnyScheduler.  The code builds successfully, but as soon as it tries to load the app, it crashes, pointing to the "eraseToAnyScheduler()" call.  This also occurs if I try to type erase locally with a labeled queue.

**To Reproduce**
[schedularTest.zip](https://github.com/pointfreeco/combine-schedulers/files/8098703/schedularTest.zip)

```swift
public struct HomeEnvironment {
  public var mainQueue: AnySchedulerOf<DispatchQueue>

  public init(
    mainQueue: AnySchedulerOf<DispatchQueue>
  ) {
    self.mainQueue = mainQueue
  }
}

@main
struct schedularTestApp: App {
  var body: some Scene {
    WindowGroup {
      ContentView(
        store: .init(
          initialState: HomeState(),
          reducer: homeReducer,
          environment: HomeEnvironment(mainQueue: .main)
        )
      )
    }
  }
}
```

**Expected behavior**
Scheduler is successfully erased and the app doesn't crash 🥲

**Screenshots**
<img width="1572" alt="image" src="https://user-images.githubusercontent.com/13445548/154723317-cd2b2283-8602-489f-a4d1-9a71b4c94bd1.png">

**Environment**
 - Xcode 13.2
 - Swift 5
 - OS: iOS 15.2

**Additional context**
This bug was initially found when the preview would crash with no feedback. I then built out a specific preview target to try and run on the simulator. This also crashed, but gave me a stack trace that pointed to the erasing of the scheduler. Because my project was pretty intense, I created a new small test project to see if it was my project or the framework (see zipped project).  Even in just this small app that only imports the latest release of the composable architecture, the bug still persists. I then tested on a device, and the bug was not there.  My device was running iOS 15.1.  I downloaded the 15.0 simulators and those do not have this bug either.  It only appears to occur with iOS 15.2.

**Comment by mbrandonw** [comment]
Hi @FlyDaddyDev,

I'm not able to reproduce the problem when I run your sample project. It seems to run just fine:

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/135203/154764779-6489bf9b-e138-404d-9ca7-067d0ddfaa57.png">

I'm using Xcode 13.2 and then iOS 15.2 simulator.

Honestly it would be very strange for Swift to crash when erasing a scheduler. There isn't anything all that special happening in those lines of code. It feels like there may be something else going on.

Could you paste the stack trace of where the crash is happening? You should be able to just highlight all the stacks from Xcode and paste them into this issue.

**Comment by FlyDaddyDev** [comment]
Hey @mbrandonw,
Thanks for taking a look into this.  I agree with your statement about it failing on erasing a scheduler, and I was assuming it is probably something on my end since you haven't been hounded about this issue since 15.2 came out.  I've attached a screen shot, and the stack trace.  Hopefully it has all the details you were looking for.

![Screen Shot 2022-02-18 at 6 42 00 PM](https://user-images.githubusercontent.com/13445548/154778691-8d6e9a86-9ff2-4532-8393-3aadb80745a3.png)


```Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000180a189f8 in swift::_getWitnessTable(swift::TargetProtocolConformanceDescriptor<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*, void const* const*) ()
#1	0x000000010045510c in lazy protocol witness table accessor for type OS_dispatch_queue and conformance OS_dispatch_queue ()
#2	0x000000010045502c in static AnyScheduler<>.main.getter at /Users/markheussner/Library/Developer/Xcode/DerivedData/schedularTest-fgabbmfosgjjgldhzymcnwzdvonu/SourcePackages/checkouts/combine-schedulers/Sources/CombineSchedulers/AnyScheduler.swift:248
#3	0x0000000100362c2c in closure #1 in schedularTestApp.body.getter at /Users/markheussner/Desktop/Development/schedularTest/Shared/schedularTestApp.swift:18
#4	0x000000010c352364 in WindowGroup.init(content:) ()
#5	0x0000000100362a8c in schedularTestApp.body.getter at /Users/markheussner/Desktop/Development/schedularTest/Shared/schedularTestApp.swift:13
#6	0x0000000100362dec in protocol witness for App.body.getter in conformance schedularTestApp ()
#7	0x000000010bdfa354 in partial apply for closure #1 in AppBodyAccessor.updateBody(of:changed:) ()
#8	0x000000010c3453f4 in closure #1 in BodyAccessor.setBody(_:) ()
#9	0x000000010bdf9c1c in AppBodyAccessor.updateBody(of:changed:) ()
#10	0x000000010c3455b0 in StaticBody.updateValue() ()
#11	0x000000010c513780 in partial apply for implicit closure #2 in implicit closure #1 in closure #1 in closure #1 in Attribute.init<τ_0_0>(_:) ()
#12	0x00000001021d1d20 in AG::Graph::UpdateStack::update() ()
#13	0x00000001021d22cc in AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) ()
#14	0x00000001021d88d0 in AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, AGSwiftMetadata const*, unsigned char&, long) ()
#15	0x00000001021ee628 in AGGraphGetValue ()
#16	0x000000010c3454a0 in StaticBody.container.getter ()
#17	0x000000010c345594 in StaticBody.updateValue() ()
#18	0x000000010c513780 in partial apply for implicit closure #2 in implicit closure #1 in closure #1 in closure #1 in Attribute.init<τ_0_0>(_:) ()
#19	0x00000001021d1d20 in AG::Graph::UpdateStack::update() ()
#20	0x00000001021d22cc in AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) ()
#21	0x00000001021d88d0 in AG::Graph::input_value_ref_slow(AG::data::ptr<AG::Node>, AG::AttributeID, unsigned int, AGSwiftMetadata const*, unsigned char&, long) ()
#22	0x00000001021ee628 in AGGraphGetValue ()
#23	0x000000010c352c58 in WindowGroupSceneList.MakeList.id.getter ()
#24	0x000000010c352cf4 in WindowGroupSceneList.MakeList.updateValue() ()
#25	0x000000010bd60778 in partial apply for specialized implicit closure #2 in implicit closure #1 in closure #1 in closure #1 in Attribute.init<τ_0_0>(_:) ()
#26	0x00000001021d1d20 in AG::Graph::UpdateStack::update() ()
#27	0x00000001021d22cc in AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) ()
#28	0x00000001021d81ac in AG::Graph::value_ref(AG::AttributeID, AGSwiftMetadata const*, unsigned char&) ()
#29	0x00000001021ee674 in AGGraphGetValue ()
#30	0x000000010bdf8f20 in AppGraph.sceneList() ()
#31	0x000000010c74d594 in AppSceneDelegate.makeSceneHost(restorationSceneItemID:restorationData:userActivity:urlContexts:) ()
#32	0x000000010c74bc2c in AppSceneDelegate.scene(_:willConnectTo:options:) ()
#33	0x000000010c74c4e0 in @objc AppSceneDelegate.scene(_:willConnectTo:options:) ()
#34	0x00000001222b9a30 in +[UIScene _sceneForFBSScene:create:withSession:connectionOptions:] ()
#35	0x0000000122e740ec in -[UIApplication _connectUISceneFromFBSScene:transitionContext:] ()
#36	0x0000000122e74588 in -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] ()
#37	0x0000000122948904 in -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] ()
#38	0x0000000105ae5a84 in -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] ()
#39	0x0000000105b11cec in __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.180 ()
#40	0x0000000105af4160 in -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] ()
#41	0x0000000105b11908 in __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke ()
#42	0x0000000101781694 in _dispatch_client_callout ()
#43	0x00000001017849cc in _dispatch_block_invoke_direct ()
#44	0x0000000105b379a0 in __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ ()
#45	0x0000000105b37878 in -[FBSSerialQueue _targetQueue_performNextIfPossible] ()
#46	0x0000000105b379d0 in -[FBSSerialQueue _performNextFromRunLoopSource] ()
#47	0x00000001030792c0 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#48	0x00000001030791c8 in __CFRunLoopDoSource0 ()
#49	0x00000001030785b8 in __CFRunLoopDoSources0 ()
#50	0x0000000103072b9c in __CFRunLoopRun ()
#51	0x00000001030723a8 in CFRunLoopRunSpecific ()
#52	0x00000001015935ec in GSEventRunModal ()
#53	0x0000000122e727ac in -[UIApplication _run] ()
#54	0x0000000122e772e8 in UIApplicationMain ()
#55	0x000000010c58c7f4 in closure #1 in KitRendererCommon(_:) ()
#56	0x000000010c58c750 in runApp<τ_0_0>(_:) ()
#57	0x000000010bfe24f4 in static App.main() ()
#58	0x0000000100362d74 in static schedularTestApp.$main() at /Users/markheussner/Desktop/Development/schedularTest/Shared/schedularTestApp.swift:10
#59	0x0000000100362e14 in main ()
#60	0x000000010092dca0 in start_sim ()
#61	0x00000001009e50fc in start ()
Thread 2 Queue : com.apple.root.background-qos (concurrent)
Thread 3Thread 4Thread 5com.apple.uikit.eventfetch-thread (6)Thread 7Thread 8Thread 9

**Comment by FlyDaddyDev** [comment]
Update:  It looks like the issue is specific to Xcode 13.2.  I opened my test project on my other computer that has Xcode 13.2.1 and the issue does not present itself.   I'm assuming the first listed bug fix might be the issue I'm seeing that was fixed with 13.2.1.  

![image](https://user-images.githubusercontent.com/13445548/154807476-8f08a876-06c3-421f-acbe-e0889c9ccf32.png)

**Comment by mbrandonw** [comment]
Ah yeah, that does seem likely to be the issue. Looks like I was testing in Xcode 13.2.1, not 13.2 like I originally stated.

Do you think we should close this issue out? Or convert to a discussion?

**Comment by FlyDaddyDev** [comment]
Closing is fine.  I'm sure most are already on 13.2.1 and if not, this issue will be here if they come looking for help 😄

**Comment by azatZul** [comment]
Hey @mbrandonw,
I started a new project on Xcode 13.3.1 with Swift 5.6 and I can confirm that I have the same issue on iOS 15.4 simulator.
EXC_BAD_ACCESS on `_getWitnessTable`
